let a = 10
let b = 20
console.log (a > b);
let c = a + b;
let d = a * b;
{
    console.log('Value of a =' + ' ' + c );
    console.log('Value of a =' + ' ' + d );
}
    let x = 45;
console.log (x > 95) 
{ 
    console.log('student is brilliant \n');
}
console.log (x < 30)
{ 
    console.log('student is poor');
}
console.log(x < 95 && x > 30)
{
    console.log ('student is \f adverage and \f getting the concept');
}
    let i = 0;
    console.log (i < 5)
    console.log ('hello', 'hello');

    